name: Latest release

on:
  push:
    branches:
      - 'main'
    
jobs:
  unit_tests:
    uses: ./.github/workflows/unit_tests.yml
    with:
      dotnet-version: '9'
      test-project-path: 'src/CyclicalFileWatcher.UnitTests'
  
  deploy_main_nuget:
    uses: abatar1/DotNetNugetWorkflow/.github/workflows/deploy-nuget.yml@v1.0.0
    needs: [ unit_tests ]
    with:
      dotnet-version: '9'
      project-name: src/CyclicalFileWatcher
      version-fragment: 'feature'
      nuget-name: 'CyclicalFileWatcher'
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
